### PR TITLE
Changed app-crypt/gnupg version to 2.0.19

### PR DESCRIPTION
**Pull request by udiudi**
2.0.9 is incorrect and causing problems when using this recipe.
Check support ticket 98862 for more info/context.

### CODE REVIEW

**Comment by tpoland** [comment]
We need to validate against 2009 stack.

**Comment by dvalfre** [comment]
@tpoland the v2 (2009) stack has available package `app-crypt/gnupg-2.0.19`.  Shall this suffice? or shall the recipe be made smart enough to decide between 2.0.9 for v2 and 2.0.19 for v4?

**Comment by tpoland** [comment]
This will solve the immediate need. It might be a good idea to gate this with a not_if/only_if so that it won't run if the change would be a downgrade to an existing package.

**Comment by tpoland** [comment]
This PR is superseded by [PR #310 ](https://github.com/engineyard/ey-cloud-recipes/pull/310/files).

**Pull request closed without merging**
