### PR TITLE
Adding Classiclink cookbook

### PR DESCRIPTION
**Pull request by paulasaurus**
Adds cookbook to automate Classiclinking of EC2 Classic instances to manually created VPCs for peering purposes.

### CODE REVIEW

**Comment by dvalfre** [comment]
Looks good to me.  @radamanthus can you review this as well?  Thanks!

**Comment by paulasaurus** [comment]
Hey @radamanthus, no need to merge this just yet, I'm going to make some further changes to the recipe's functionality first.

**Comment by paulasaurus** [comment]
Recipe updated, ready for merging.

**Comment by AlexMorreale** [comment]
possibly squash commits :D

**Comment by rbankston** [comment]
Looks good to me

**Pull request merged**
